### ISSUE TITLE
Error on run `yiisoftware/yii-php:8.*-fpm-nginx`

### ISSUE THREAD

**Issue by vjik** [yiisoft/yii-docker#35]
`docker-compose.yml`:

```
version: '3'

services:
  php:
    image: yiisoftware/yii-php:8.2-fpm-nginx
    working_dir: /app
    volumes:
      - ./:/app
      # host-volume for composer cache
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
    ports:
      - '30080:80'
```

Console:

```
❯ docker compose up
[+] Running 2/2
 ✔ Network app_default  Created                                                                  0.1s
 ✔ Container app-php-1  Created                                                                  2.5s
Attaching to app-php-1
app-php-1  | usermod: no changes
app-php-1  | Error: Format string '%(ENV_SUPERVISOR_START_FPM)s' for 'program:php-fpm.autostart' contains names ('ENV_SUPERVISOR_START_FPM') which cannot be expanded. Available names: ENV_COMPOSER_ALLOW_SUPERUSER, ENV_GPG_KEYS, ENV_HOME, ENV_HOSTNAME, ENV_LC_CTYPE, ENV_PATH, ENV_PHPIZE_DEPS, ENV_PHP_ASC_URL, ENV_PHP_CFLAGS, ENV_PHP_CPPFLAGS, ENV_PHP_ENABLE_XDEBUG, ENV_PHP_INI_DIR, ENV_PHP_LDFLAGS, ENV_PHP_SHA256, ENV_PHP_URL, ENV_PHP_USER_ID, ENV_PHP_VERSION, ENV_PS1, ENV_PWD, ENV_TERM, group_name, here, host_node_name, program_name in section 'program:php-fpm' (file: '/etc/supervisor/conf.d/fpm.conf')
app-php-1  | For help, use /usr/bin/supervisord -h
app-php-1 exited with code 2
```

Same problem with `yiisoftware/yii-php:8.1-fpm-nginx`.
